# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
  About: /about
  Tags: /tags
  Categories: /categories
  Contact: /contact

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY


# Comments.
comments:
  # Disqus comments
  disqus_shortname: ethanyan6

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/?lang=en
facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
dribble_url: https://dribbble.com/
github_url: https://github.com/EthanYan6
googleplus_url: https://plus.google.com/
behance_url: https://www.behance.net/
fivehundredpx_url: https://500px.com/
email_url: yanyuliang6@163.com
rss_url: \#

# Footer About Text
footer_about: "This website is the exclusive blog of Ethan Yan. If there is any infringement, please inform us in time. I will delete it in the first time. If you try to find my contact information, you may be disappointed, hahahahahahaha......For more exciting articles, please follow my Wechat public account(Subscriptions)『Pythonnote』or『全栈技术精选』"

# Footer Copyright Line
footer_copyright: "@Untitled. All right reserved | Design by Ethan Yan"

